### ISSUE TITLE
Function.caller used to retrieve strict caller

### ISSUE THREAD

**Issue by YerkoPalma** [mantoni/choo-test#1]
I'm getting this error when I try to run a `choo-test` with mochify. My test script is the following

``` javascript
const chooTest = require('choo-test')
const assert = require('assert')
const mainView = require('../src/views/main')
const userModel = require('../src/models/user')

describe('choo-app', () => {
  let app

  beforeEach(() => {
    app = chooTest()
    app.model(userModel)
    app.router((route) => [route('/', mainView)])
    app.start()
  })

  afterEach(() => {
    app.restore()
  })

  it('renders the view', () => {
    const b = app.$('h1')
    assert.equal(b.className, 'global-header')
  })
})
```

And after run, with `$ mochify` I get the following stacktrace:

``` text
1) choo-app "before each" hook for "renders the view":
     Function.caller used to retrieve strict caller
      belCreateElement node_modules/choo/node_modules/yo-yo/node_modules/bel/index.js:68
      node_modules/choo/node_modules/yo-yo/node_modules/bel/node_modules/hyperx/node_modules/hyperscript-attribute-to-property/index.js:17
      node_modules/choo/node_modules/yo-yo/node_modules/bel/node_modules/hyperx/index.js:44
      mainView src/views/main.js:6
      chooWrap node_modules/choo/index.js:139
      emit node_modules/choo/node_modules/sheet-router/node_modules/wayfarer/index.js:48
      match node_modules/choo/node_modules/sheet-router/index.js:55
      start node_modules/choo/index.js:74
      start node_modules/choo-test/lib/choo-test.js:50
      test/views.js:14

Error: Exit 1
```

Any idea why this error is happening?

**Comment by mantoni** [comment]
Thanks for reporting. I also crashed into this. Does your script file or view implementation have `'use strict';`? If yes, then that is your issue, caused by `bel` [here](https://github.com/shama/bel/blob/master/index.js#L68).

**Comment by YerkoPalma** [comment]
@mantoni I'm not using `use strict` in any of my files. But I just found that there is a package I'm using ([localforage](https://github.com/localForage/localForage)) which use the strict mode. Is there any workaround for this? Anyway it looks more like a bel issue.

**Comment by mantoni** [comment]
Hm. Which exact versions of choo and choo-test are you using? Maybe something changed? There is also a `use strict` statement in the main `choo-test` file. Can you try removing it in your `node_modules` and see whether that fixes it?

**Comment by YerkoPalma** [comment]
**choo version: 3.2.2**
**choo-test version: 0.0.5**

I removed the `use strict` sentence from choo-test and localforage in my node_modules, but still got the same error. Now my view code is this

``` javascript
const html = require('choo/html')
const localforage = require('localforage')
const input = require('../components/input')

const mainView = (state, prev, send) => {
  return html`
    <div class="container" onload=${loadLocalState(this, state, send)}>
      <h1 class="h1 global-header">Welcome <span class="global-header-highlight">${state.user.username}</span></h1>
      ${input(state, send)}
    </div>
  `
}

module.exports = mainView

function loadLocalState (element, state, send) {
  return function () {
    if (state.user.initial && process.env.NODE_ENV !== 'test') {
      localforage.getItem('app').then(localState => {
        send('user:init', { localState })
      }).catch(err => {
        console.log(err)
      })
    }
  }
}
```

I completly removed the localforage part, so the `onload`event call a noop function, and still failling. Now I later erased the `onload` call from my view and the test got executed normally. That makes sense as the line that you linked is inside the [`onload`](https://github.com/shama/bel/blob/master/index.js#L59-L71) hook of bel code. Maybe that call from bel is not compatible with phantomJs?

**Comment by mantoni** [comment]
PhantomJS is a good hint. Which version of PhantomJS are you using?

**Comment by mantoni** [comment]
Also, I'd like and try to reproduce exactly the same thing as you have. Mind pushing it somewhere?

**Comment by YerkoPalma** [comment]
I can't push right now to Github, I will do in a few hours. Perhaps you can see the code [here](https://c9.io/yerkopalma/choo-genesis/files/). I'm using mochify 2.18.1 which use phantomjs 2.1.7.

Oh and thanks for your patience :smile:

**Comment by YerkoPalma** [comment]
@mantoni sorry for the delay, here is [the repo](https://github.com/YerkoPalma/choo-genesis) where I'm having this issue. Thanks for your help :)

**Comment by mantoni** [comment]
Ok, it turns out that your babel setup inserts `"use strict"` statements into your views. You can see this when you run

```
node_modules/.bin/browserify . | less
```

and then search for `mainView` and scroll a little up to the top function scope.

The reason why I couldn't reproduce is because I'm using `es2040` (which is also based on babel, afaik) but does not insert `"use strict"` statements for reasons that I don't yet understand.

I tried to fix your example by removing `babel` and the preset and use `es2040` instead, but then I got

```
Error: Couldn't find preset "es2015" relative to directory \
  ".../choo-genesis" while parsing file: .../view.js
```

So yeah, not a `choo-test` issue. More a `bel` / `babel` combination issue - very unfortunate 😒

**Comment by YerkoPalma** [comment]
Wow, thanks for the detailed feedback :tada: . I'll look into this soon, thanks again :)
